---
- name: build_images | creating images folder if it does not exist
  file: path={{ tftpboot_dir }}/{{ item }} state=directory
  with_items: apache_tftp_links

- name: build_images | downloading isos
  get_url: url={{ item.url }}/{{ item.file }} dest={{ tftpboot_dir }}/images/{{ item.file }} force=no
  with_items: tftp_iso_images

- name: build_images | creating tftp_images_folders
  file: path={{ tftpboot_dir }}/images/{{ item }} state=directory
  with_items: tftp_images_folders
  when: tftp_images_folders is defined

- name: build_images | unmouting iso images
  mount: name={{ tftpboot_dir }}/images/{{ item.folder }} src={{ tftpboot_dir }}/images/{{ item.file }} fstype=iso9660 state=unmounted
  with_items: tftp_iso_images

- name: build_images | unmouting VMware iso images
  mount: name={{ tftpboot_dir }}/images/{{ item.folder }} src={{ tftpboot_dir }}/images/{{ item.file }} fstype=iso9660 state=unmounted
  with_items: vmware_iso_images

- name: build_images | setting tftpboot_dir folder permissions
  file: path={{ tftpboot_dir }} state=directory recurse=yes owner=nobody group=nogroup

- name: build_images | mouting iso images
  mount: name={{ tftpboot_dir }}/images/{{ item.folder }} src={{ tftpboot_dir }}/images/{{ item.file }} fstype=iso9660 state=mounted
  with_items: tftp_iso_images

- name: build_images | checking that VMware iso images exist
  stat: path={{ tftpboot_dir }}/images/{{ item.file }}
  register: vmware_isos
  with_items: vmware_iso_images
  when: vmware_iso_images is defined

- name: build_images | mouting VMware iso images
  mount: name={{ tftpboot_dir }}/images/{{ item.folder }} src={{ tftpboot_dir}}/images/{{ item.file }} fstype=iso9660 state=mounted
  with_items: vmware_iso_images
  when: vmware_iso_images is defined and vmware_isos.results[0].stat.exists

- name: build_images | configuring apache2
  file: src={{ tftpboot_dir }}/{{ item }} dest={{ apache_root }}/{{ item }} owner=www-data group=www-data state=link
  with_items: apache_tftp_links
