#- name: build_images | Uploading DIAG
#  file:
#    src: "siad-firmware//DIAG-{{ siad_ufi_diag_version }}/ONIE.bin/onie-installer-Ubuntu.16.04_{{ siad_ufi_diag_version }}_dhcp.bin"
#    dest: "{{ tftpserver_tftpboot_dir }}/onie-installer/onie-installer.bin"
#    owner: "{{ web_user }}"
#    group: "{{ web_group }}"
#
#- name: build_images | Uploading NOS
#  file:
#    src: "siad-firmware/vyatta/NOS_Chesterfield_{{ siad_vyatta_version }}/vyatta-{{ siad_vyatta_version }}-amd64-vrouter.iso-ONIE.bin"
#    dest: "{{ tftpserver_tftpboot_dir }}/nos-installer/onie-installer.bin"
#    owner: "{{ web_user }}"
#    group: "{{ web_group }}"

- name: build_images | Generate SIAD build script environment file
  template:
    src: att-siad-ufi-scripts/env.sh.j2
    dest: '{{ role_path }}/files/att-siad-ufi-scripts/scripts/env.sh'
  delegate_to: localhost

- name: build_images | Copy SIAD Build Scripts
  synchronize:
    src: att-siad-ufi-scripts/scripts/
    dest: '{{ tftpserver_tftpboot_dir }}/siad/scripts/'
    delete: yes
    recursive: yes
    owner: no
    group: no

- name: build_images | Upload SIAD Firmware Images
  synchronize:
    src: 'siad-firmware/{{ item }}/'
    dest: '{{ tftpserver_tftpboot_dir }}/siad/{{ item }}/'
    delete: yes
    recursive: yes
    owner: no
    group: no
  with_items:
    - 10ge-kr
    - bios
    - bmc
    - bsp
    - cpu_cpld
    - i210
    - mb_cpld
    - ucd
    - vyatta
    - diag

- name: build_images | Configuring Apache2 links to ONIE Install Binaries
  file:
    src: "{{ tftpserver_tftpboot_dir }}/siad/{{ item.dest }}"
    dest: "{{ tftpserver_apache_root }}/{{ item.name }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    state: "link"
  with_items: '{{ tftpserver_bin_images }}'
  when: tftpserver_bin_images is defined

- name: Fix SIAD Build Script and Firmware permissions
  file:
    path: '{{ tftpserver_tftpboot_dir }}/siad/'
    state: directory
    recurse: yes
    mode: 0755
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
